const fs = require('fs');

const base64_192 = "iVBORw0KGgoAAAANSUhEUgAAAMAAAADAAQMAAAA2Z1M1AAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAACNJREFUeF7twTEBAAAAwqD1T+1pDaAAAAAAAAAAAAAAAAAAeA0wAAE+GzAAAAAASUVORK5CYII=";
const base64_512 = "iVBORw0KGgoAAAANSUhEUgAAAgAAAAIAAQMAAADOtka5AAAAA1BMVEUAAACnej3aAAAAAXRSTlMAQObYZgAAAGJJREFUeF7twQEBAAAAgJD+r+4ICgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4N0AAAQG09iAAAAAASUVORK5CYII=";

fs.writeFileSync('public/icon-192x192.png', Buffer.from(base64_192, 'base64'));
fs.writeFileSync('public/icon-512x512.png', Buffer.from(base64_512, 'base64'));

console.log('Icons created');
